# ============================================================
# setup-env.ps1
# Run this from the project root in VS Code terminal:
#   .\setup-env.ps1
#
# Prompts for each Firebase value and writes .env
# Values are entered in your terminal — never sent to Claude
# ============================================================

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  EA Environment Setup" -ForegroundColor Cyan
Write-Host "  RMcManus Holdings LLC" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Get these values from:" -ForegroundColor Yellow
Write-Host "  Firebase Console -> Project Settings -> Your Apps -> Web App" -ForegroundColor Yellow
Write-Host ""

# --- Collect values ---

$apiKey = Read-Host "Firebase API Key"
$authDomain = Read-Host "Auth Domain (e.g. your-project.firebaseapp.com)"
$projectId = Read-Host "Project ID (e.g. rmcmanus-ea)"

# Storage bucket is always {projectId}.appspot.com (or .firebasestorage.app for newer projects)
# We'll default it but allow override
$defaultBucket = "$projectId.appspot.com"
Write-Host ""
Write-Host "Storage Bucket — press Enter to accept default [$defaultBucket]" -ForegroundColor Gray
$storageBucket = Read-Host "Storage Bucket"
if ([string]::IsNullOrWhiteSpace($storageBucket)) {
    $storageBucket = $defaultBucket
}

$messagingSenderId = Read-Host "Messaging Sender ID (numeric)"
$appId = Read-Host "App ID (1:xxxxxxx:web:xxxxxxx)"

Write-Host ""
Write-Host "VAPID Key (optional — leave blank to skip push notifications for now)" -ForegroundColor Gray
$vapidKey = Read-Host "VAPID Key"

# --- Write .env ---

$envContent = @"
# AI Executive Assistant — RMcManus Holdings LLC
# Generated by setup-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# DO NOT commit this file to version control

# Firebase Web App Config
REACT_APP_FIREBASE_API_KEY="AIzaSyA_Ady_SFEFaW1DZNwX-9aUQ-DhOO7oVoU"ey
REACT_APP_FIREBASE_AUTH_DOMAIN="ramdesignworks-exec-staff.firebaseapp.com"
REACT_APP_FIREBASE_PROJECT_ID="ramdesignworks-exec-staff"
REACT_APP_FIREBASE_STORAGE_BUCKET="ramdesignworks-exec-staff.firebasestorage.app"
REACT_APP_FIREBASE_MESSAGING_SENDER_ID="347930374163"
REACT_APP_FIREBASE_APP_ID="1:347930374163:web:17c8e015df86c78504cfe6"

# Firebase Cloud Messaging — VAPID key for push notifications
# Get from: Firebase Console -> Project Settings -> Cloud Messaging -> Web configuration
REACT_APP_FIREBASE_VAPID_KEY=$vapidKey
"@

$envPath = Join-Path $PSScriptRoot ".env"
Set-Content -Path $envPath -Value $envContent -Encoding UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  .env written successfully" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""

# --- Also update firebase-messaging-sw.js with the config ---
# The service worker can't read .env — it needs the values baked in at build time
# For now, update the placeholders in firebase-messaging-sw.js

$swPath = Join-Path $PSScriptRoot "public\firebase-messaging-sw.js"
if (Test-Path $swPath) {
    $swContent = Get-Content $swPath -Raw
    $swContent = $swContent `
        -replace "__FIREBASE_API_KEY__", $apiKey `
        -replace "__FIREBASE_AUTH_DOMAIN__", $authDomain `
        -replace "__FIREBASE_PROJECT_ID__", $projectId `
        -replace "__FIREBASE_STORAGE_BUCKET__", $storageBucket `
        -replace "__FIREBASE_MESSAGING_SENDER_ID__", $messagingSenderId `
        -replace "__FIREBASE_APP_ID__", $appId
    Set-Content -Path $swPath -Value $swContent -Encoding UTF8
    Write-Host "firebase-messaging-sw.js updated with your config" -ForegroundColor Green
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. In Firebase Console, enable Authentication (Email/Password)" -ForegroundColor White
Write-Host "  2. Create your user account: Authentication -> Add User" -ForegroundColor White
Write-Host "  3. Enable Firestore Database (Start in production mode)" -ForegroundColor White
Write-Host "  4. Run: npm start" -ForegroundColor White
Write-Host ""
